name: Maven Build

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.7
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '1.7'
        jdkFile: 'jdk7u80-b32' 

    - name: Build with Maven
      run: |
        mvn clean test
        mvn clean verify -P integration-test
        mvn clean verify -P all-tests

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
