name: Maven Build

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt' 

    - name: Build with Maven
      run: |
        mvn clean test
        mvn clean verify -P integration-test
        mvn clean verify -P all-tests

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
